JWT logic added for FastAPI source code (#4)
* fix: secrets to vars

* feat(cicd): retry plus ansible logic and README doc enhancement

* feat: added fastapi src code

* ci: missing --load flag

* ci: remove extra ||

* "fix: use gzip instead of bzip2"

* feat: update env name

* feat(ci): ci and src code test update

* doc: added

* deploy: with non prod jwt token in place

* deploy: retry due to missing jose deps

* deploy: removing need for jwt secret, relient on httpx and jwt signing keys

* feat: resolving no module problem with __init__ file

* feat: JWT applied across all enpoints except /health

* fix: TypeError: APIRoute.__init__() missing 2 required positional arguments: path and endpoint

* fix: TypeError: <lambda>() takes 0 positional arguments but 1 was given

* feature: attempt to protect all routes via app.dependencies

* revert: attempt failed, reverting

* feat(attempt): adding auth middleware

* fix: redudant user param on 2 endpoints removed

* fix: crash when endpoint gets triggered

* fix: crash due to NameError: name JSONResponse is not defined